### ISSUE TITLE
What up with the declandewet/common-tags repo?

### ISSUE THREAD

**Issue by dancoates** [zspecza/common-tags#214]
This repo (https://github.com/declandewet/common-tags) is linked in the package.json and appears on the npm package page

https://www.npmjs.com/package/common-tags

it appears that it was recently taken over by this person: https://hackerone.com/codermak?type=user

Is access to that repo tied at all to the ability to alter the code of this repo or to publish the common-tags package?

**Comment by fatfisz** [comment]
That's a shame; I can only assure you that the repo is still in the right hands.

It looks like the lib's creator Declan de Wet has changed his GitHub handle to `zspecza` and the `declandewet` handle was indeed taken over by some random person. The unfortunate result is that while previously GitHub redirected from 
https://github.com/declandewet/common-tags to https://github.com/zspecza/common-tags, this doesn't happen anymore.

I'm struggling to find time to follow up with this project's roadmap, but I'll at least take care of the problem, since it's very misleading. I'll be releasing a new version with the updated repo link soon ™️ (I don't have internet at my new home yet, this should be resolved in a matter of days).

In the meantime I'm pinning this issue for posterity. I won't be contacting the person who took over the `declandewet` handle, because I don't think it's going to be productive.

**Comment by dancoates** [comment]
Thanks @fatfisz that makes sense, and it is reassuring that there isn't any risk to this project.

**Comment by fatfisz** [comment]
I just published a new version to npm, at least that's what `npm info` is telling me:
![image](https://user-images.githubusercontent.com/6004414/141354596-e3e4e54e-2693-48ab-8715-589f36538a64.png)

The version on the npm page is still 1.8.0, probably because of caching. I'll close the issue once I see new links working there.

**Comment by fatfisz** [comment]
... and it works!
![image](https://user-images.githubusercontent.com/6004414/141360067-7b5e05d5-0971-4b5f-bed5-d2ddf7efca68.png)

**Comment by dancoates** [comment]
brilliant, thanks @fatfisz for the quick update
